# Generated by Django 4.1.5 on 2023-01-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('orange', 'Orange'), ('blue', 'Blue'), ('red', 'Red')], max_length=50)),
                ('seq_number', models.IntegerField()),
            ],
        ),
    ]
